// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateNewWorld(arg1, arg2, arg3, arg4, arg5, arg6, arg7) {
  return window['go']['main']['App']['CreateNewWorld'](arg1, arg2, arg3, arg4, arg5, arg6, arg7);
}

export function ExistingCheck(arg1) {
  return window['go']['main']['App']['ExistingCheck'](arg1);
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function ListWorlds() {
  return window['go']['main']['App']['ListWorlds']();
}

export function LoadGameFromString(arg1) {
  return window['go']['main']['App']['LoadGameFromString'](arg1);
}

export function SaveGame(arg1) {
  return window['go']['main']['App']['SaveGame'](arg1);
}

export function Shutdown() {
  return window['go']['main']['App']['Shutdown']();
}

export function TestingFunction() {
  return window['go']['main']['App']['TestingFunction']();
}
