// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateNewWorld(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string,arg6:string,arg7:string):Promise<string>;

export function ExistingCheck(arg1:string):Promise<void>;

export function Greet(arg1:string):Promise<string>;

export function ListWorlds():Promise<string>;

export function LoadGameFromString(arg1:string):Promise<string>;

export function SaveGame(arg1:string):Promise<void>;

export function Shutdown():Promise<void>;

export function TestingFunction():Promise<void>;
